from __future__ import annotations

import json
import urllib.error
import urllib.request


def slack(webhook_url: str, blocks: list) -> None:
    """POST a Block Kit message to a Slack Incoming Webhook URL."""
    payload = json.dumps({"blocks": blocks}).encode()
    req = urllib.request.Request(
        webhook_url,
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        urllib.request.urlopen(req, timeout=10)
    except urllib.error.HTTPError as exc:
        raise RuntimeError(
            f"Slack webhook returned HTTP {exc.code}: {exc.read().decode()}"
        ) from exc


def build_cost_blocks(title: str, rows: list[dict], period_label: str) -> list:
    """Build Slack Block Kit blocks for a cost breakdown table."""
    total = sum(r["cost"] for r in rows)
    lines = [f"• *{r['name']}*: ${r['cost']:,.2f}" for r in rows[:20]]
    body = "\n".join(lines) or "_No cost data found._"

    return [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": title, "emoji": True},
        },
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Period*\n{period_label}"},
                {"type": "mrkdwn", "text": f"*Total Spend*\n${total:,.2f}"},
            ],
        },
        {"type": "divider"},
        {"type": "section", "text": {"type": "mrkdwn", "text": body}},
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": "Generated by _aws-cost-cli_"}
            ],
        },
    ]
